// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {valorant} from '../models';

export function GetSessionInfo():Promise<valorant.SessionResponse>;
